### ISSUE TITLE
array subclasses

### ISSUE THREAD

**Issue by az0977776** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#10]
Just wondering about the signatures of the get and push. What is the point of having different subclasses for the array if you still need to cast the Object to the correct type. Also none of the functions in array are virtual.

**Comment by EthanGriffee** [comment]
The purpose of the subclasses is just to overright the get and put functions to guarantee that all the elements of the array are of the type specified.  I added casting because due to the signatures, it will always return an Object*. I wasn't 100% sure that they needed to be virtual but, there is no harm with them being virtual so i added that in.

**Comment by az0977776** [comment]
what happens if you try to push a non string into the stringarray?

**Comment by EthanGriffee** [comment]
It would throw an exception

**Comment by EthanGriffee** [comment]
I added tests using google test it expect exit(1)
