### ISSUE TITLE
set index out of range

### ISSUE THREAD

**Issue by barthch** [EthanGriffee/Ethan-and-Divit-Part-2-Software-Dev#9]
What should we do if the index given is greater than array->size()? Same thing for get(index).

please add comments and tests.

**Comment by EthanGriffee** [comment]
Hi, I am currently changing the code and tests based on the statement "Arrays should grow when values are pushed back, and otherwise support reads and writes."  In A2. I interoperate that to mean that  this should be implemented as an Arraylist instead of an Array, and this will be changing the tests to reflect that. I will be also adding Wrapper Objects for Boolean, Int, Float, and StringArray. FloatArray, ect. I am not sure how to implement errors in test.cpp. Expect the change shortly. Sorry for the delay

**Comment by barthch** [comment]
CwC does not have errors to throw. Thus we cannot comply with spec for set.

**Comment by EthanGriffee** [comment]
Yeah I was thinking of exception and exits, I can / will add Google Test mentioned in piazza for testing these

**Comment by EthanGriffee** [comment]
Ok I added tests using google test
